[2024-10-08T16:39:47.423+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T16:39:47.435+0900] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mnist_model_workflow.new_data_sensor scheduled__2024-10-08T06:30:00+00:00 [queued]>
[2024-10-08T16:39:47.441+0900] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mnist_model_workflow.new_data_sensor scheduled__2024-10-08T06:30:00+00:00 [queued]>
[2024-10-08T16:39:47.441+0900] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-08T16:39:47.454+0900] {taskinstance.py:2888} INFO - Executing <Task(FileSensor): new_data_sensor> on 2024-10-08 06:30:00+00:00
[2024-10-08T16:39:47.468+0900] {standard_task_runner.py:72} INFO - Started process 25158 to run task
[2024-10-08T16:39:47.480+0900] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'mnist_model_workflow', 'new_data_sensor', 'scheduled__2024-10-08T06:30:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/mnist_model_dag.py', '--cfg-path', '/var/folders/tx/bcbxk5bj33x4r2rt041m7bmr0000gn/T/tmpt2zir_3h']
[2024-10-08T16:39:47.482+0900] {standard_task_runner.py:105} INFO - Job 7: Subtask new_data_sensor
[2024-10-08T16:39:47.540+0900] {task_command.py:467} INFO - Running <TaskInstance: mnist_model_workflow.new_data_sensor scheduled__2024-10-08T06:30:00+00:00 [running]> on host hyowon-kim-macbook-pro.local
[2024-10-08T16:39:47.606+0900] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='mnist_model_workflow' AIRFLOW_CTX_TASK_ID='new_data_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T06:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-08T06:30:00+00:00'
[2024-10-08T16:39:47.608+0900] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-08T16:39:47.609+0900] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-08T16:39:47.609+0900] {logging_mixin.py:190} INFO - Current task name:new_data_sensor state:running start_date:2024-10-08 07:39:47.435272+00:00
[2024-10-08T16:39:47.610+0900] {logging_mixin.py:190} INFO - Dag name:mnist_model_workflow and current dag run status:running
[2024-10-08T16:39:47.610+0900] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-08T16:39:47.611+0900] {baseoperator.py:405} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-10-08T16:39:47.618+0900] {base.py:84} INFO - Retrieving connection 'fs_default'
[2024-10-08T16:39:47.618+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.{jpg,png,jpeg}
[2024-10-08T16:40:47.620+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.{jpg,png,jpeg}
[2024-10-08T16:41:47.621+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.{jpg,png,jpeg}
[2024-10-08T16:42:47.622+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.{jpg,png,jpeg}
[2024-10-08T16:43:47.623+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.{jpg,png,jpeg}
[2024-10-08T16:44:47.625+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.{jpg,png,jpeg}
[2024-10-08T16:45:47.626+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.{jpg,png,jpeg}
[2024-10-08T16:46:47.628+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.{jpg,png,jpeg}
[2024-10-08T16:47:47.630+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.{jpg,png,jpeg}
[2024-10-08T16:48:47.631+0900] {filesystem.py:109} INFO - Poking for file /Users/alookso/1007MLpj/ml-project-ml-pjt-7/uploads/*.{jpg,png,jpeg}
[2024-10-08T16:49:43.409+0900] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-10-08T16:49:43.428+0900] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 25158. PIDs of all processes in the group: [25158]
[2024-10-08T16:49:43.428+0900] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 25158
[2024-10-08T16:49:43.428+0900] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-10-08T16:49:43.433+0900] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/sensors/filesystem.py", line 123, in execute
    super().execute(context=context)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/sensors/base.py", line 334, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/Users/alookso/1007MLpj/myenv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-10-08T16:49:43.440+0900] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-08T16:49:43.441+0900] {logging_mixin.py:190} INFO - Task start:2024-10-08 07:39:47.435272+00:00 end:2024-10-08 07:49:43.440375+00:00 duration:596.005103
[2024-10-08T16:49:43.442+0900] {logging_mixin.py:190} INFO - Task:<Task(FileSensor): new_data_sensor> dag:<DAG: mnist_model_workflow> dagrun:<DagRun mnist_model_workflow @ 2024-10-08 06:30:00+00:00: scheduled__2024-10-08T06:30:00+00:00, state:running, queued_at: 2024-10-08 06:38:50.323488+00:00. externally triggered: False>
[2024-10-08T16:49:43.442+0900] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-10-08T16:49:43.443+0900] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=mnist_model_workflow, task_id=new_data_sensor, run_id=scheduled__2024-10-08T06:30:00+00:00, execution_date=20241008T063000, start_date=20241008T073947, end_date=20241008T074943
[2024-10-08T16:49:43.454+0900] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-08T16:49:43.486+0900] {process_utils.py:80} INFO - Process psutil.Process(pid=25158, status='terminated', exitcode=2, started='16:39:47') (25158) terminated with exit code 2
[2024-10-08T16:49:51.753+0900] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-08T16:49:51.764+0900] {taskinstance.py:2602} INFO - Dependencies not met for <TaskInstance: mnist_model_workflow.new_data_sensor scheduled__2024-10-08T06:30:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2024-10-08T16:49:51.765+0900] {local_task_job_runner.py:166} INFO - Task is not able to be run
